database:
  tables :
    # default table
    tb_userdata:
      id_userdata:
        type: serial
        notNull: True
        primaryKey: True
      first_name:
        type: varchar
        notNull: True
      last_name:
        type: varchar
        notNull: True
      location:
        type: varchar
      email:
        type: varchar
        unique: True

    tb_user:
      id_user:
        type: serial
        notNull: True
        primaryKey: True
      id_userdata:
        type: int
        notNull: True
        foreignKey:
          reference: tb_userdata
          field: id_userdata
          on_delete: cascade
          on_update: cascade
      username:
        type: varchar
        unique: True
      password:
        type: varchar
    # default table end

    point_test:
      id_pointest:
        type: serial
        notNull: True
        primaryKey: True
      nm_pointest:
        type: varchar
      value_pointest:
        type: varchar
